### ISSUE TITLE
PHP Fatal error:  Cannot redeclare view()

### ISSUE THREAD

**Issue by barkap** [senaranya/laravel-adminer#1]
Package does not work. There is a fatal php error after logging in (or immediately after opening route in case AdminerAutologinController is used).

`PHP Fatal error:  Cannot redeclare view() (previously declared in /www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:1003) in /www/laravel/vendor/aranyasen/laravel-adminer/src/adminer-4.7.0-en.php on line 490`

Laravel Framework 5.7.19.

Edit: I noticed that this error happens with PostgreSQL but not with MySQL. I also tested the included adminer source file (adminer-4.7.0-en.php) by itself separately from laravel without any errors when using postgres.

**Comment by senaranya** [comment]
Great find! Turns out Adminer has more conflicting `view()` methods than I initially found! Can you please try with the attached file - unzip and replace the existing _vendor/aranyasen/laravel-adminer/src/adminer-4.7.0-en.php_ with it on your environment please?
I have tested with both MySQL and Postgres after the fix and seems to be working well now

[adminer-4.7.0-en.php.zip](https://github.com/senaranya/laravel-adminer/files/2709488/adminer-4.7.0-en.php.zip)

**Comment by barkap** [comment]
Fix seems to be working fine.

**Comment by senaranya** [comment]
Fixed at [v1.0.1](https://github.com/senaranya/laravel-adminer/releases/tag/1.0.1)
